### GENERAL SETTINGS ###

# Site settings
title: GOST
description: "GOST is an open source implementation of the SensorThings API in the Go programming language initiated by Geodan. It contains easily deployable server software and a Javascript client. The software can be installed on many platforms/devices (e.g. Windows, Linux, Mac OS and Raspberry Pi)"
analytics: UA-88292336-1
baseurl: "" #important: start with /
url: "http://gost.github.io"

# Other settings
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

disqus_shortname: gost-1

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:
  text_dark: "#505151"
  primary: "#e8e8e8" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Geodan
    - President Kennedylaan 1
    - 1079 MB Amsterdam
tel: +31 (0)20 – 5711 311

# Members information. Shown on About page.
members:
  - name: Tim Ebben
    position: Researcher GEO-IT
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: twitter
        url: https://twitter.com/berttemme
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Since 1985, Geodan has grown into one of the leading geo-ICT companies in our country. We specialise in the provision of spatial information and are experienced in applying new, innovative technologies"
